name: ADAF_Ocean
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - arrow-cpp=17.0.0=h865e1df_1
  - asttokens=3.0.0=py310h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.11.212=hecad206_0
  - blas=1.0=mkl
  - bokeh=3.6.2=pyhd8ed1ab_1
  - boost-cpp=1.78.0=he72f1d9_0
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotli-python=1.0.9=py310hd8f1fbe_7
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cartopy=0.22.0=py310h1128e8f_0
  - certifi=2025.7.14=py310h06a4308_0
  - cftime=1.6.4=py310h5eee18b_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=pyh707e725_0
  - cloudpickle=3.1.0=pyhd8ed1ab_2
  - comm=0.2.1=py310h06a4308_0
  - contourpy=1.3.1=py310hdb19cb5_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=13.0=3
  - cytoolz=0.12.2=py310h5eee18b_0
  - dask=2024.12.1=pyhd8ed1ab_0
  - dask-core=2024.12.1=pyhd8ed1ab_0
  - dask-expr=1.1.21=pyhd8ed1ab_0
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - distributed=2024.12.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.17.0=py310h06a4308_0
  - freetype=2.10.4=h0708190_1
  - fsspec=2024.12.0=pyhd8ed1ab_0
  - geos=3.10.6=h6a678d5_0
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.2=h5eee18b_0
  - glog=0.5.0=h48cff8f_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - h5netcdf=1.2.0=py310h06a4308_0
  - h5py=3.12.1=py310hc0802c4_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.12.1=h2b7332f_3
  - icu=70.1=h27087fc_0
  - idna=3.7=py310h06a4308_0
  - importlib-metadata=8.5.0=pyha770c72_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py310h06a4308_1
  - ipython=8.30.0=py310h06a4308_0
  - jedi=0.19.2=py310h06a4308_0
  - jinja2=3.1.5=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_1
  - jupyter_client=8.6.3=py310h06a4308_0
  - jupyter_core=5.8.1=py310h06a4308_0
  - kiwisolver=1.4.8=py310h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.15.0.42=0
  - libcurand=10.4.0.35=h50d9014_0
  - libcurl=8.11.1=hc9e6f67_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnetcdf=4.8.1=h14805e7_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libzip=1.8.0=h6ac8c49_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.2=py310h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib-base=3.10.0=py310hbfdbfaf_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - msgpack-python=1.0.3=py310hd09550d_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - netcdf4=1.6.2=py310h6d89c78_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py310h06a4308_0
  - numexpr=2.10.1=py310h3c60e43_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.17=h5eee18b_0
  - orc=2.0.1=h2d29ad5_0
  - packaging=24.2=py310h06a4308_0
  - pandas=2.2.3=py310h6a678d5_0
  - parso=0.8.4=py310h06a4308_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pexpect=4.9.0=py310h06a4308_0
  - pillow=11.0.0=py310hcea889d_1
  - pip=24.2=py310h06a4308_0
  - proj=9.3.1=he5811b7_0
  - prompt-toolkit=3.0.43=py310h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=17.0.0=py310h1128e8f_0
  - pyproj=3.6.1=py310h6370d16_0
  - pyshp=2.3.1=py310h06a4308_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.5.1=py3.10_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py310h06a4308_0
  - pyyaml=6.0=py310h5764c6d_4
  - pyzmq=26.2.0=py310h6a678d5_0
  - re2=2022.04.01=h27087fc_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.4=py310h06a4308_0
  - s2n=1.3.27=hdbd6064_0
  - setuptools=75.1.0=py310h06a4308_0
  - shapely=2.0.6=py310h6f81d3c_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6a678d5_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tblib=3.0.0=pyhd8ed1ab_1
  - tk=8.6.14=h39e8969_0
  - toolz=1.0.0=pyhd8ed1ab_1
  - torchaudio=2.5.1=py310_cu118
  - torchtriton=3.1.0=py310
  - torchvision=0.20.1=py310_cu118
  - tornado=6.4.2=py310h5eee18b_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing_extensions=4.12.2=py310h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py310h5eee18b_1
  - urllib3=2.2.1=pyhd8ed1ab_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.13=py310h06a4308_0
  - wheel=0.44.0=py310h06a4308_0
  - xarray=2024.11.0=py310h06a4308_0
  - xyzservices=2024.9.0=pyhd8ed1ab_1
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h6a678d5_0
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - black==25.1.0
      - boto3==1.40.2
      - botocore==1.40.2
      - cf-xarray==0.10.6
      - colorama==0.4.6
      - cycler==0.12.1
      - dgl==2.1.0
      - einops==0.8.1
      - executing==2.1.0
      - fairscale==0.4.13
      - fonttools==4.55.4
      - frozenlist==1.7.0
      - global-land-mask==1.0.0
      - hf-xet==1.1.5
      - huggingface-hub==0.34.3
      - icecream==2.1.3
      - jmespath==1.0.1
      - lightning-utilities==0.15.1
      - llvmlite==0.45.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - multidict==6.6.3
      - mypy-extensions==1.1.0
      - numba==0.62.0
      - nvidia-ml-py==12.575.51
      - pathspec==0.12.1
      - platformdirs==4.3.8
      - prettytable==3.16.0
      - propcache==0.3.2
      - protobuf==6.31.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyecharts==2.0.8
      - pygments==2.18.0
      - pynvml==12.0.0
      - pyparsing==3.2.1
      - pytorch-lightning==2.5.2
      - rich==13.9.4
      - ruamel-yaml==0.18.14
      - ruamel-yaml-clib==0.2.12
      - s3transfer==0.13.1
      - safetensors==0.5.3
      - scipy==1.15.3
      - seaborn==0.13.2
      - simplejson==3.20.1
      - sparse==0.17.0
      - str2bool==1.1
      - swankit==0.2.4
      - swanlab==0.6.8
      - sympy==1.13.1
      - thop==0.1.1-2209072238
      - timm==1.0.19
      - tomli==2.2.1
      - torchdata==0.11.0
      - torchmetrics==1.8.0
      - tqdm==4.67.1
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - wrapt==1.17.2
      - xesmf==0.8.10
      - yarl==1.20.1
prefix: /home/mamuyuan/.conda/envs/xyf
